title: "[Idea] "
labels: ["enhancement", "idea"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve SOURCE? We'd love to hear it! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this idea solve? What gap does it fill?
      placeholder: "Example: It's difficult to identify IPs from specific ASNs without manual filtering..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: "Example: Add an ASN filter column or create separate files grouped by ASN..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Approaches
      description: Have you considered other ways to solve this problem?
      placeholder: "Example: Alternatively, we could add a Python script that generates filtered subsets..."

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of enhancement is this?
      options:
        - New Data Source
        - New Export Format
        - Visualization Improvement
        - Performance Optimization
        - Documentation Enhancement
        - API/Query Enhancement
        - Automation/CI Improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Potential Impact
      description: How would this benefit the community?
      options:
        - High - Would benefit most users
        - Medium - Would benefit specific use cases
        - Low - Nice to have
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this idea
        - label: I can provide test data or use cases
